### ISSUE TITLE
Explore the possibility of integration of the SRTM15+V2.nc file as base datasource.

### ISSUE THREAD

**Issue by jreniel** [JaimeCalzadaNOAA/geomesh#4]

**Comment by jreniel** [comment]
Permission granted by UCSD. Link to publication: http://topex.ucsd.edu/sandwell/publications/180_Tozer_SRTM15+.pdf

**Comment by jreniel** [comment]
Reopened to track implementation of SRTM topobathy into geomesh as supplementary data.

**Comment by JaimeCalzadaNOAA** [comment]
Project specific data, such as the SRTM15+v2.nc need not be referenced directly in the geomesh module. However, implementation was done on the geomesh.Raster class that enables the usage of large rasters via windowed reading. In that sense, the SRTM14+V2.nc is still supported, along with other large DEM files.
